### PR TITLE
try to fix tests

### PR DESCRIPTION
**Pull request by lucidrains**

### CODE REVIEW

**Comment by amorehead** [comment]
I noticed pytest breaking for my fork too, and the only thing that fixed it was to scale down the number of rollout steps and model size for the `test_pdbinput_input()` unit test (since that one was getting canceled for me somehow)

**Comment by lucidrains** [comment]
@amorehead your code looks great!

**Comment by amorehead** [comment]
@lucidrains, I noticed that lowering `dim_pairwise` fixed the issue for me, so I think you're right

**Comment by lucidrains** [comment]
@amorehead yah, the CI boxes actually are even more resource constrained (at least compared to my macbook)

**Pull request merged**
