### PR TITLE
The alignment error should be a pairwise error.

### PR DESCRIPTION
**Pull request by gitabtion**
Following Alg. 30, the alignment error should be a pairwise error.

### CODE REVIEW

**Comment by lucidrains** [comment]
@gitabtion thank you Heng! also pinging @engelberger just so he can double check!

**Comment by engelberger** [comment]
lgtm! thank you for catching my error

**Comment by lucidrains** [comment]
@engelberger thank you for reviewing it!

**Comment by engelberger** [comment]
I have dying to contribute more again but the PhD have engulfed me 😪

**Comment by lucidrains** [comment]
understandable! you've contributed far more than most already 🙏

**Pull request merged**
