### PR TITLE
AlphaFold3Input to mmCIF File Format via BioMolecule 

### PR DESCRIPTION
**Pull request by dhuvik**
This PR Introduces

1.  A new function alphafold3_input_to_biomolecule

2. Makes the following changes to Biomolecule's to_mmcif()
- One potentially breaking change from sorted to np.array.sort() that goes from
[np.int64(0), np.int64(1), np.int64(2), ... np.int64(260)]
to what I believe is the desired: [  0   1   2   ...  260]

Many non-breaking changes that adapt the code to include ligand and metals with incomplete information and de-novo structure fields. (Line comments added)

^ I think we might need to update life.py and some of the ligand_constants but wanted to introduce this as a preliminary to get feedback and go back to solidify and clean code.

Currently WIP, could definitely use some review :)

### CODE REVIEW

**Comment by amorehead** [comment]
Beautiful. This is perfect timing for this conversion function, since Phil has already started to build out a `cli.py` for inference.

On first glance, I'm thinking we could use this (in an unintuitive way) to feed the constructed `biomols` into `pdb_input_to_molecule_input()` (by first wrapping these `biomols` within a `PDBInput` instance). The reason for doing this is, the `pdb_input_to_molecule_input()` pipeline is ultimately what is used for training, validation, and testing (and it supports MSA and template parsing, among parsing of other more complicated features), so it makes sense to me to try to unify what you have in this PR with the `pdb_input_to_molecule_input` pathway. Ultimately, what we'll need for inference is a sampled structure corresponding to a user's `Alphafold3Input` and then a `Biomolecule` representation of that `Alphafold3Input` so we can insert the sampled atom coordinates (corresponding to the `Alphafold3Input`) into the respective `Biomolecule` and then export an mmCIF (in the same style as the AlphaFold Server) using the `to_mmcif()` function (and the `mmcif_metadata.py` file).

I'll revisit this PR in a few hours to try to give more concrete feedback on the code itself and what needs to do be done to merge the code in.

**Comment by lucidrains** [comment]
@dhuvik this looks great Dhuvi! throw in a test for [this function](https://github.com/lucidrains/alphafold3-pytorch/pull/230/files#diff-d9ef3fd4aa7bdcb874a94b20063712f0f680a68ec93a10ce87b737d17f78cc39R1825) and i'll merge and wire it up to the cli! after Alex gives his blessing too

**Comment by dhuvik** [comment]
Thank you gentlemen <3. Will go ahead and get started on the test for it right away. 

@amorehead Oooh I think unifying it with `pdb_input_to_molecule_input` will definitely be very useful. With all the training on synthetic data that's being done across domains, I think we would be well served by supporting code that feeds the inference outputs to the training scripts. I'll poke around with the `pdb_input_to_molecule_input` and await your thoughts on the code impl in the meantime.

**Comment by lucidrains** [comment]
@dhuvik shape rotator indeed

had to look that up 🤣

**Comment by dhuvik** [comment]
All good sir, you've been on an absolute tear with all the other PRs you're juggling. I'll go ahead and make that change + add in the tests. Will mess around with a more detailed annotation for the ligands and metals after we merge. Thank you both for your time and guidance 🤗

**Comment by lucidrains** [comment]
@dhuvik looks great Dhuvi the shape rotator 🚀 let's get this merged!

**Comment by dhuvik** [comment]
> @dhuvik looks great Dhuvi the shape rotator 🚀 let's get this merged!

Not to be dramatic or anything but I'm framing this ^

**Comment by amorehead** [comment]
Great effort, @dhuvik! Note that I recently added a `PDBInput.inference` boolean flag to `PDBInputs` that you should be able to hook onto when you implement your `Alphafold3Input` -> `Biomolecule` -> `pdb_input_to_molecule_input()` logic. Essentially, I'm imagining that you can just use `pdb_input.inference` to skip or modify any part of `pdb_input_to_molecule_input()` that isn't applicable to inference inputs.

**Comment by amorehead** [comment]
Also, @dhuvik, in my fork, I'm seeing for `to_inference_mmcif()` the following lines (may not perfectly match yours, but they are under the metal ion case handling if branch) being highlighted by my linter: 

```bash
alphafold3_pytorch/common/biomolecule.py:1824:57: F821 undefined name 'type_symbol'
alphafold3_pytorch/common/biomolecule.py:1825:59: F821 undefined name 'unique_atom_name'
alphafold3_pytorch/common/biomolecule.py:1839:63: F821 undefined name 'b_factor'
alphafold3_pytorch/common/biomolecule.py:1843:58: F821 undefined name 'unique_atom_name'
```

**Pull request merged**
