### PR TITLE
Add new embeddings

### PR DESCRIPTION
**Pull request by amorehead**
* Adds new embeddings such as pLM features

### CODE REVIEW

**Comment by lucidrains** [comment]
add a test and we are good to go! 🎉

**Comment by amorehead** [comment]
Test for which function?

**Comment by lucidrains** [comment]
@amorehead just covering [this span of logic](https://github.com/lucidrains/alphafold3-pytorch/pull/252/files#diff-78267e29bdb5d839b0ac6bbc79ba348881b8a67891777aa3b87207598313e39cR6564-R6574)

**Comment by amorehead** [comment]
@lucidrains sg. I've added a test in [this commit](https://github.com/lucidrains/alphafold3-pytorch/pull/252/commits/a9773f204f998e083e6f9b9853613257462f012e)

**Pull request merged**
