### PR TITLE
Add spatial and spatial interface cropping functions for `Biomolecules`

### PR DESCRIPTION
**Pull request by amorehead**
* Adds the spatial and spatial interface cropping functions for `Biomolecules` following the AF3 supplement

### CODE REVIEW

**Comment by amorehead** [comment]
I've seen the error `RuntimeError: Cannot subclass _TensorBase directly` show up in my fork's unit tests as well. What is causing it? It doesn't seem to occur every time I push a change though...

**Comment by lucidrains** [comment]
@amorehead so it turns out an update to pytorch broke `torchtyping` which is a dependency of `jaxtyping` still

i'll just force an earlier version of pytorch for testing until Patrick or someone gets in a fix https://github.com/patrick-kidger/torchtyping/issues/48

**Comment by amorehead** [comment]
I bumped into Patrick yesterday at ICML, perhaps I can ask him to push a patch? ;)

**Comment by lucidrains** [comment]
@amorehead if he's in your DM! lol

hope you shook his hand, his library played a big role for this project (reckon it would have taken twice or three times as long without)

**Comment by amorehead** [comment]
He did mention that open sourcing AF3 sounds interesting, so there's that

**Comment by lucidrains** [comment]
@amorehead guaranteed that his startup is looking into it, just not disclosed

in fact, every protein AI company out there is looking at this, just most of them won't lift a finger

**Pull request merged**
