### PR TITLE
Add `WeightedSamplerPDB`

### PR DESCRIPTION
**Pull request by vandrw**
Introduced a sampler that implements the algorithm described in Section 2.5.1 of the AlphaFold 3 supplement. In the current version, iterating on this object will return a list of strings, referencing IDs to PDB items (e.g., `['6lr1', '2v33', '3bs1', ..., '2ktf']`). These can then be used to load the corresponding `.cif` files during training.

The `__iter__()` function of the sampler uses the `sample()` method, but since I was not entirely sure what the original paper was describing, I implemented a secondary `cluster_based_sample()` function to handle a slightly different approach. This method first samples a number of unique `cluster_ids`, and then samples one molecule from each according to the normalized in-cluster weights. However, this function is noticeably slower than the simpler `sample()` (avg. 19.78 ms/it vs 445.75 ms/it). This could be optimized further by calculating the in-cluster weights beforehand, but I wanted to see what everyone else thinks before making optimizations.

One other issue that should be discussed for the default sampling approach is whether we should indicate which chain is the target, in case it is part of an interface. There is a chance that a molecule will be sampled multiple times in a batch, since a `pdb_id` can reference both an interface, and multiple chains. This is also not really mitigated with the `cluster_based_sample()` approach, as we can still sample the same `pdb_id` (max. 2 times) from the chain and interface mappings. I could probably indicate this by appending the chain IDs to the PDB ID (e.g., `121d_A_B` for an interface, `121d_A` for the chain).

Finally, I already rewrote the code in the repository to use Polars instead of Pandas, and I could push those changes after I have tested them. I could also rewrite this code to implement Pandas instead to avoid having both, if it is required for other libraries you are using. Otherwise, I would suggest we make use of the improved parallelization that Polars offers for training.

### CODE REVIEW

**Comment by lucidrains** [comment]
@vandrw this looks good Andrei! would you like to try moving the code you have under the "is main" condition to a pytest function?

**Comment by amorehead** [comment]
Great effort, @vandrw. Perhaps we can also rename the file to `weighted_pdb_dataset.py` to better describe the main class within this script?

**Comment by vandrw** [comment]
I implemented the changes, plus pushed the changes to change from Pandas to Polars. I tried testing the changes, but the cluster IDs for interfaces fluctuate from run to run, which made it a bit hard to determine if it is a correct implementation. Can @amorehead check it out?

**Comment by amorehead** [comment]
Hey, @vandrw. Can you clarify where you are seeing interface cluster IDs fluctuate? Are you referring to the new `WeightedPDBDataset` you pushed? Or is this in the `cluster_pdb_dataset.py` instead?

**Comment by vandrw** [comment]
Yes, it's in the `cluster_pdb_dataset.py`. If I run the original code multiple times and save each `interface_cluster_mapping.csv`, I can observe that the maximum value for the `interface_cluster_id` keeps changing. Same thing with the Polars implementation.

**Comment by amorehead** [comment]
OK. To debug, are you also clearing out the `*_chain_clusters.csv` files each run, which would have MMseqs2 rerun each time?

**Comment by vandrw** [comment]
Yes. I've been deleting all `*_cluster_mapping.csv` files and reruning with mmseq. I will try again in a few hours, once I am back home, to debug further. But just to have a starting point, could the cluster_ids be differing because of the parallelization?

**Comment by amorehead** [comment]
Have you been deleting the `data/pdb_data/data_caches/clusterings/all_chain_sequences.json` and `data/pdb_data/data_caches/clusterings/interface_chain_ids.json` files each run as well? If not, I suspect MMseqs2 may be assigning some chains different chain cluster IDs each run, which may then impact how many interface clusters are found by the script. Otherwise, off the top of my head, I can't think of anything in the clustering script that would be non-deterministic run-to-run (unless someone else can find something).

**Comment by vandrw** [comment]
> If it's the chain and interface extraction code that's causing this non-determinism in clustering, one solution is for everyone to use the all_chain_sequences.json and interface_chain_ids.json files uploaded to [OneDrive](https://mailmissouri-my.sharepoint.com/:f:/g/personal/acmwhb_umsystem_edu/EqU8tjUmmKxJr-FAlq4tzaIBi2TIBtmw5Vl3k_kmgNlepA?e=mzlyv6) so we don't encounter this issue repeatedly. If it's MMseqs2 that's causing the stochasticity, then we can have folks also use the chain cluster mapping CSVs uploaded to [OneDrive](https://mailmissouri-my.sharepoint.com/:f:/g/personal/acmwhb_umsystem_edu/EqU8tjUmmKxJr-FAlq4tzaIBi2TIBtmw5Vl3k_kmgNlepA?e=mzlyv6) (and just redo the interface clustering as desired).

Thanks for the suggestions! I did not delete the `.json` files. Looking at it a bit deeper, the `*_chain` files have the same number of clusters, albeit with different cluster IDs assigned to each molecule. Running the original code with Pandas resulted in 84716 interfaces the first time, and 84734 the second time. There was also a small difference in the number of nucleic acid clusters, resulting in 10147 the first time and 10146 the second time. The Polars implementation showed very similar results, so I suspect that the new code does the same thing, and the difference is due to MMseqs2. The original `cluster_pdb_mmcifs.py` script with Pandas took ~1m 35s to recreate all the `*_cluster_mapping.csv` files, while the Polars implementation took ~1m 3s. The overall speed up on my machine seems to be around 30s. It's not a big improvement, but we can skip the `pandas` dependency :)

What I also should double check is whether the datetime conversion works correctly in the new `filter_pdb_mmcifs.py`. I tried to test it out, but I couldn't easily find any examples in the PDB data that had a header containing a `release_date`. Do you happen to know any such entires in the dataset? If not, how would the format for the date look like (e.g., `%Y-%m-%d`)?

Finally, going back to the main point, I might have made a mistake with the sampler. Are the `cluster_ids` for ligands, proteins, nucleic acids, peptides and proteins different from each other? For example, items in cluster 0 for proteins should not be associated with items in cluster 0 for peptides. I'll correct this quickly if that is the case.

**Comment by amorehead** [comment]
@vandrw, on [this line](https://github.com/lucidrains/alphafold3-pytorch/blob/2804bbab7c5f06d597c0ee5c5dafe618ea8297ab/scripts/filter_pdb_mmcifs.py#L725) of the filtering script, what should happen is that two versions of the same PDB complex should be loaded into memory at the same time (i.e., the `assembly1` version and the `asym` unit version). The `assembly1` versions of each PDB complex mmCIF file sadly (and for some odd reason) do not include a large portion of metadata (such as release date headers) that the corresponding `asym` unit mmCIF files do. In which case, we have to load both versions into memory at once and "impute" the header metadata (and a few other important pieces of information only available in the `asym` unit file) into the original `assembly1` `MmcifObject` (which we ultimately want to parse the sequence and structure from for filtering and clustering).

Regarding clustering, this is a great point. It's important to note that the cluster_ids` for the protein, nucleic acid, peptide, and ligand clusters will overlap with each other by design, since they are essentially `aranges`. However, the cluster IDs within these `chain_mapping` CSV files should be distinguished from one another based on which file they were loaded from. In other words, even though protein chain cluster 0 and ligand chain cluster 0 share the same index, they represent different clusters entirely (since these represent different "chains" or segments within the original PDB complex).

**Comment by amorehead** [comment]
@vandrw, I just went through all your weighted sampling code, and it looks great! Regarding needing to distinguish cluster IDs for different molecule types, I just created a [PR](https://github.com/lucidrains/alphafold3-pytorch/pull/96) (that looks bigger than it actually is) to address this concern. The sampler now returns a tuple of three strings: a PDB ID, a first chain ID, and (for interfaces only) a second chain ID (left as an empty string for single chains that were sampled).

**Comment by vandrw** [comment]
@amorehead Really sorry for the oversight, it seems that I was using the unfiltered data when loading them. I think everything is good on that front! I initially used the `date_parser` from `dateutil` to infer the format automatically, but I see now that the format is Year-Month-Day, so I will change it to `dateutil.strptime(str_date, "%Y-%m-%d)` to avoid surprises (i.e., inferring it as Year-Day-Month). It shouldn't matter much, as the cut-off point is mainly the year.

Also, thanks for letting me know about the cluster_ids. ~I will make another pull request with the correct cluster ID arrangement.~ It seems I was not fast enough, haha! I will look at what changes you made now :)

**Pull request merged**
