### PR TITLE
Replace squared distance with abs, increase number of bins by 1

### PR DESCRIPTION
**Pull request by vandrw**

### CODE REVIEW

**Comment by lucidrains** [comment]
@vandrw oh, they don't use squaring?

**Comment by vandrw** [comment]
They use squaring, but from my test it looks like we don't need it. This is their code:
```py
dgram = torch.sum(
        (pos[..., None, :] - pos[..., None, :, :]) ** 2, dim=-1, keepdim=True
    )
lower = torch.linspace(min_bin, max_bin, no_bins, device=pos.device) ** 2
```

Instead of applying a root over it, they simply square the bins as well to avoid that. I think we can skip this.

**Comment by vandrw** [comment]
Apologies for the failed check. I know where the issue is, and I'll come back in a second with a fix. It seems that the tests on my machine get a SIGKILL after a while, so I can't test properly there. I assume it's due to the size of the model?

**Comment by lucidrains** [comment]
> Apologies for the failed check. I know where the issue is, and I'll come back in a second with a fix. It seems that the tests on my machine get a SIGKILL after a while, so I can't test properly there. I assume it's due to the size of the model?

yea, probably oom

have you tried running the specific test? `pytest tests/test_af3.py -k test_model_selection_score_end_to_end` for the error you are running into

**Comment by lucidrains** [comment]
@vandrw the error comes from the pde and pae breaks, which need to be adjusted too, but realistically should inherit the bins from `Alphafold3` `https://github.com/lucidrains/alphafold3-pytorch/blob/main/alphafold3_pytorch/alphafold3.py#L4535-L4536`

**Comment by vandrw** [comment]
@lucidrains I'll dig a bit further. The `*_breaks: Float[" pae_break"] = torch.arange(0, 31.5, 0.5)` were probably due to using the bin centres, right? Would we also have to increase the step size to 1.0 here?

**Comment by lucidrains** [comment]
@vandrw haha no worries, take your time

yea, may be two separate ways to represent the bins going on and should be standardized

**Comment by amorehead** [comment]
@vandrw, I've created a [new PR](https://github.com/lucidrains/alphafold3-pytorch/pull/213) to replace this PR, where the new PR standardizes all distogram binning default values to match the AF3 paper

**Comment by amorehead** [comment]
If you could help us with standardizing the lddt/plddt code as well, that'd be super helpful. I suspect that could be improved as well with closer inspection.

**Pull request closed without merging**
