### PR TITLE
(WIP) Simplify `life.py` by switching to template residue SMILES strings

### PR DESCRIPTION
**Pull request by amorehead**
* WIP PR
* Simplifies `life.py` by switching to template residue SMILES strings
* Will resume development tomorrow, as desired feel free to build on this to save time

### CODE REVIEW

**Comment by lucidrains** [comment]
@amorehead looks great! 🙏 the only thing is that this would change where the phospho / peptide bond is marked [here](https://github.com/lucidrains/alphafold3-pytorch/blob/main/alphafold3_pytorch/inputs.py#L358-L359)

i'll probably pull bits and pieces from this PR as we move towards variable monomer atom lengths

**Comment by lucidrains** [comment]
@amorehead for these new smiles provided, is the N and C terminus first and last atoms?

**Comment by amorehead** [comment]
@lucidrains, for the phospho/peptide bonds linked above, are they necessary? I don't think AF3's training relies on polymer-polymer (e.g., protein-protein) bonds. They said they used polymer-ligand and ligand-ligand bonds and bonds less than 2.4 Angstrom in distance (during training), but at inference time, the polymer-ligand (and inter-ligand) bonds are not supplied

**Comment by lucidrains** [comment]
@amorehead i think it wouldn't hurt to just make sure to give special care to this bookkeeping

i'll take care of it 👍

**Comment by amorehead** [comment]
Yeah, the safe bet is to handle most types of bonds just in case. It will simply make training more likely to succeed.

**Comment by lucidrains** [comment]
> Yeah, the safe bet is to handle most types of bonds just in case. It will simply make training more likely to succeed.

yea you know, this is where some ablation on the atomic resolution stuff would have helped, in particular the attention biasing.

**Comment by amorehead** [comment]
Actually, I agree more now after thinking about it. I think what they meant in the AF3 paper now is something like this: For both training and inference, the model automatically featurizes an atom-atom distance less than 2.4 Angstrom as a bond. This information is always available, since it's just based on distances. However, for training in particular, AF3 is also provided explicit (correct) indications of polymer-ligand and ligand-ligand bonds, since it sounds like these bonds might be hard for the model to learn early on in training otherwise. However, after training, the model should no longer need to be told that polymer-ligand and ligand-ligand bonds need to be formed during structure prediction.

**Comment by lucidrains** [comment]
@amorehead yea, not all bonds are provided, but i assume the atom bonds for the polymer chains are

**Comment by amorehead** [comment]
This WIP PR is now out of date, so I'll just close it ;)

**Pull request closed without merging**
