### PR TITLE
Fix bug in construction of atom indices à la `PDBInput`

### PR DESCRIPTION
**Pull request by amorehead**
* Fixes a bug in the construction of atom indices à la `PDBInput` that could cause two (or more) separate ligands to be accidentally grouped together if they share the same residue index but not the same chain index, leading to e.g., distogram atom indices being out-of-bounds for the total number of atoms in a complex.
* N.b., for what it's worth, this was one of the trickiest bugs to identify to date. On AMD cards, all you'd get is a generic `HIPError` to go debug, with no reference to an out-of-index error in the e.g., distogram modeling code. On NVIDIA cards, you'd actually get the expected out-of-index error to trigger further debugging.

### CODE REVIEW

**Comment by lucidrains** [comment]
@Kaihui-Cheng ^

**Comment by Kaihui-Cheng** [comment]
That's great! I think it works! Thank Alex and Lucidrains!

**Comment by lucidrains** [comment]
It's all Alex

**Comment by Kaihui-Cheng** [comment]
Thanks! By the way,  lucidrains, it might be helpful to add a `device` parameter in `cli.py`. Currently, all inference is running on the CPU.

**Comment by lucidrains** [comment]
@Kaihui-Cheng ok done! let me know if it works or not

**Comment by Kaihui-Cheng** [comment]
We might also need to move the `input data` to the device:

https://github.com/lucidrains/alphafold3-pytorch/blob/3e1795ea03d4d3956940ef3cefdd566c5e36911b/alphafold3_pytorch/alphafold3.py#L6338

**Comment by lucidrains** [comment]
@Kaihui-Cheng good catch, should work now

**Comment by Kaihui-Cheng** [comment]
Yeah! it works!

**Pull request merged**
